/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finaldec4discrete;

import java.awt.event.KeyEvent;
import java.math.BigInteger;
import javax.swing.JOptionPane;

/**
 *
 * @author XcmoiZoe
 */
public class Pascal extends javax.swing.JFrame {

    /**
     * Creates new form Pascal
     */
    public Pascal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        num0 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(733, 489));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("       PASCAL  TRIANGLE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 10, 530, 90);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTER  K:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 140, 70, 30);

        num0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num0KeyTyped(evt);
            }
        });
        getContentPane().add(num0);
        num0.setBounds(140, 140, 40, 30);

        area.setEditable(false);
        area.setBackground(new java.awt.Color(0, 0, 0));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        area.setForeground(new java.awt.Color(0, 204, 0));
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 120, 470, 290);

        jButton1.setText("COMPUTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 180, 120, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finaldec4discrete/home.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 390, 60, 50);

        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 250, 120, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finaldec4discrete/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 690, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     class function1{
    public void formula() 
    {
    }
    }
    
    class pscal extends function1{
       public void formula(){
         
          BigInteger r= BigInteger.valueOf(Integer.parseInt(num0.getText()));
             if(num0.getText().equals("") )
                  {
                  JOptionPane.showMessageDialog(null,"DONT LEAVE IT BLANK ^_^");
                   } 
             else{
                 if(!r.equals(BigInteger.ZERO) && r.compareTo(BigInteger.valueOf(500))<=0){
                         
                          BigInteger number;
                         
                 for(BigInteger i=BigInteger.ZERO;i.compareTo(r)<0;i=i.add(BigInteger.ONE))
		{
			for(BigInteger k=r; k.compareTo(i)>1;k=k.subtract(BigInteger.ONE))
			{
                             area.append(" ");
			}
                      number = BigInteger.valueOf(1);
			for(BigInteger j=BigInteger.ZERO;j.compareTo(i)<=0;j=j.add(BigInteger.ONE))
			{
				area.append(number+ " ");
                 number = number.multiply(i.subtract(j)).divide(j.add(BigInteger.ONE)); 
			}area.append(" \n");
			
		}               
             }else{
                 JOptionPane.showMessageDialog(null,"Sorry Invalid Input(n<r)&&(1-500 only)");
                 }
             }
           

//       else{
//                 JOptionPane.showMessageDialog(null,"Sorry Invalid Input(n<r)&&(1-500 only)");
//            }
//       
    
    }}
    
    private void num0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num0KeyTyped
              char mander=evt.getKeyChar();
       if(!(Character.isDigit(mander))||(mander==KeyEvent.VK_BACK_SPACE)||(mander==KeyEvent.VK_DELETE))
               {
                 evt.consume();
       }
    }//GEN-LAST:event_num0KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new index().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        function1 ptri = new pscal();
        ptri.formula();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        num0.setText("");
        area.setText(String.valueOf(""));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pascal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pascal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pascal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pascal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pascal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num0;
    // End of variables declaration//GEN-END:variables
}
